name: CMake

on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packaged dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libliquid-dev libglib2.0-dev libfftw3-dev libsoapysdr-dev libconfig++-dev

    - name: Install libacars
      run: |
        cd "$RUNNER_TEMP"
        git clone https://github.com/szpajder/libacars.git
        cd libacars
        mkdir build
        cd build
        cmake ..
        make -j
        sudo make install
        sudo ldconfig

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Test run
      run: /usr/local/bin/dumphfdl --help
